/**
 * Codes NAF (Nomenclature des Activités Françaises, rév. 2) — liste complète
 * des ~732 sous-classes officielles INSEE, organisée par section (A-U).
 */

export type NafEntry = {
  code:         string;
  label:        string;
  section:      string;
  sectionLabel: string;
};

export const NAF_SECTIONS: { code: string; label: string }[] = [
  { code: "A", label: "Agriculture, sylviculture et pêche" },
  { code: "B", label: "Industries extractives" },
  { code: "C", label: "Industrie manufacturière" },
  { code: "D", label: "Énergie électrique, gaz et vapeur" },
  { code: "E", label: "Eau, assainissement et déchets" },
  { code: "F", label: "Construction" },
  { code: "G", label: "Commerce et réparation automobile" },
  { code: "H", label: "Transports et entreposage" },
  { code: "I", label: "Hébergement et restauration" },
  { code: "J", label: "Information et communication" },
  { code: "K", label: "Finance et assurance" },
  { code: "L", label: "Activités immobilières" },
  { code: "M", label: "Activités spécialisées, scientifiques et techniques" },
  { code: "N", label: "Services administratifs et de soutien" },
  { code: "O", label: "Administration publique et défense" },
  { code: "P", label: "Enseignement" },
  { code: "Q", label: "Santé humaine et action sociale" },
  { code: "R", label: "Arts, spectacles et activités récréatives" },
  { code: "S", label: "Autres activités de services" },
  { code: "T", label: "Activités des ménages en tant qu'employeurs" },
  { code: "U", label: "Activités extraterritoriales" },
];

const A = "Agriculture, sylviculture et pêche";
const B = "Industries extractives";
const C = "Industrie manufacturière";
const D = "Énergie électrique, gaz et vapeur";
const E = "Eau, assainissement et déchets";
const F = "Construction";
const G = "Commerce et réparation automobile";
const H = "Transports et entreposage";
const I = "Hébergement et restauration";
const J = "Information et communication";
const K = "Finance et assurance";
const L = "Activités immobilières";
const M = "Activités spécialisées, scientifiques et techniques";
const N = "Services administratifs et de soutien";
const O = "Administration publique et défense";
const P = "Enseignement";
const Q = "Santé humaine et action sociale";
const R = "Arts, spectacles et activités récréatives";
const S = "Autres activités de services";
const T = "Activités des ménages en tant qu'employeurs";
const U = "Activités extraterritoriales";

function e(code: string, label: string, section: string, sectionLabel: string): NafEntry {
  return { code, label, section, sectionLabel };
}

export const NAF_CODES: NafEntry[] = [

  // ── A — Agriculture, sylviculture et pêche ───────────────────────
  e("01.11Z", "Culture de céréales (sauf riz), légumineuses et graines oléagineuses", "A", A),
  e("01.12Z", "Culture du riz", "A", A),
  e("01.13A", "Culture de légumes frais ou réfrigérés, de melons", "A", A),
  e("01.13B", "Culture de légumes, de melons, de racines et de tubercules", "A", A),
  e("01.14Z", "Culture de la canne à sucre", "A", A),
  e("01.15Z", "Culture du tabac", "A", A),
  e("01.16Z", "Culture de plantes à fibres", "A", A),
  e("01.19Z", "Autres cultures non permanentes", "A", A),
  e("01.21Z", "Culture de la vigne", "A", A),
  e("01.22Z", "Culture de fruits tropicaux et subtropicaux", "A", A),
  e("01.23Z", "Culture d'agrumes", "A", A),
  e("01.24Z", "Culture de fruits à pépins et à noyau", "A", A),
  e("01.25Z", "Culture d'autres fruits d'arbres, d'arbustes et de baies", "A", A),
  e("01.26Z", "Culture de fruits oléagineux", "A", A),
  e("01.27Z", "Culture de plantes à boissons", "A", A),
  e("01.28Z", "Culture de plantes à épices, aromatiques, médicinales et pharmaceutiques", "A", A),
  e("01.29Z", "Autres cultures permanentes", "A", A),
  e("01.30Z", "Reproduction de plantes", "A", A),
  e("01.41Z", "Élevage de vaches laitières", "A", A),
  e("01.42Z", "Élevage d'autres bovins et de buffles", "A", A),
  e("01.43Z", "Élevage de chevaux et d'autres équidés", "A", A),
  e("01.44Z", "Élevage de chameaux et d'autres camélidés", "A", A),
  e("01.45Z", "Élevage d'ovins et de caprins", "A", A),
  e("01.46Z", "Élevage de porcins", "A", A),
  e("01.47Z", "Élevage de volailles", "A", A),
  e("01.49Z", "Élevage d'autres animaux", "A", A),
  e("01.50Z", "Culture et élevage associés", "A", A),
  e("01.61Z", "Activités de soutien aux cultures", "A", A),
  e("01.62Z", "Activités de soutien à la production animale", "A", A),
  e("01.63Z", "Traitement primaire des récoltes", "A", A),
  e("01.64Z", "Traitement des semences", "A", A),
  e("01.70Z", "Chasse, piégeage et services annexes", "A", A),
  e("02.10Z", "Sylviculture et autres activités forestières", "A", A),
  e("02.20Z", "Exploitation forestière", "A", A),
  e("02.30Z", "Récolte de produits forestiers non ligneux", "A", A),
  e("02.40Z", "Services de soutien à l'exploitation forestière", "A", A),
  e("03.11Z", "Pêche en mer", "A", A),
  e("03.12Z", "Pêche en eau douce", "A", A),
  e("03.21Z", "Aquaculture en mer", "A", A),
  e("03.22Z", "Aquaculture en eau douce", "A", A),

  // ── B — Industries extractives ────────────────────────────────────
  e("05.10Z", "Extraction de houille", "B", B),
  e("05.20Z", "Extraction de lignite", "B", B),
  e("06.10Z", "Extraction de pétrole brut", "B", B),
  e("06.20Z", "Extraction de gaz naturel", "B", B),
  e("07.10Z", "Extraction de minerais de fer", "B", B),
  e("07.21Z", "Extraction de minerais d'uranium et de thorium", "B", B),
  e("07.29Z", "Extraction d'autres minerais de métaux non ferreux", "B", B),
  e("08.11Z", "Extraction de pierres ornementales et de construction", "B", B),
  e("08.12Z", "Exploitation de gravières et sablières, extraction d'argiles", "B", B),
  e("08.13Z", "Extraction de minerais pour l'industrie chimique et d'engrais naturels", "B", B),
  e("08.91Z", "Extraction de minerais pour l'industrie chimique et d'engrais naturels", "B", B),
  e("08.92Z", "Extraction de tourbe", "B", B),
  e("08.93Z", "Production de sel", "B", B),
  e("08.99Z", "Autres activités extractives n.c.a.", "B", B),
  e("09.10Z", "Activités de soutien à l'extraction d'hydrocarbures", "B", B),
  e("09.90Z", "Activités de soutien aux autres industries extractives", "B", B),

  // ── C — Industrie manufacturière ─────────────────────────────────
  e("10.11Z", "Transformation et conservation de la viande de boucherie", "C", C),
  e("10.12Z", "Transformation et conservation de la viande de volaille", "C", C),
  e("10.13A", "Préparation industrielle de produits à base de viande", "C", C),
  e("10.13B", "Charcuterie", "C", C),
  e("10.20Z", "Transformation et conservation de poisson, de crustacés et mollusques", "C", C),
  e("10.31Z", "Transformation et conservation de pommes de terre", "C", C),
  e("10.32Z", "Préparation de jus de fruits et légumes", "C", C),
  e("10.39A", "Autre transformation et conservation de légumes", "C", C),
  e("10.39B", "Transformation et conservation de fruits", "C", C),
  e("10.41A", "Fabrication d'huiles et graisses brutes", "C", C),
  e("10.41B", "Fabrication d'huiles et graisses raffinées", "C", C),
  e("10.42Z", "Fabrication de margarine et graisses comestibles similaires", "C", C),
  e("10.51A", "Fabrication de lait liquide et de produits frais", "C", C),
  e("10.51B", "Fabrication de beurre", "C", C),
  e("10.51C", "Fabrication de fromages", "C", C),
  e("10.51D", "Fabrication d'autres produits laitiers", "C", C),
  e("10.52Z", "Fabrication de glaces et sorbets", "C", C),
  e("10.61A", "Meunerie", "C", C),
  e("10.61B", "Autres activités du travail des grains", "C", C),
  e("10.62Z", "Fabrication de produits amylacés", "C", C),
  e("10.71A", "Fabrication industrielle de pain et de pâtisserie fraîche", "C", C),
  e("10.71B", "Cuisson de produits de boulangerie", "C", C),
  e("10.71C", "Boulangerie et boulangerie-pâtisserie", "C", C),
  e("10.71D", "Pâtisserie", "C", C),
  e("10.72Z", "Fabrication de biscuits, biscottes et pâtisseries de conservation", "C", C),
  e("10.73Z", "Fabrication de pâtes alimentaires", "C", C),
  e("10.81Z", "Fabrication de sucre", "C", C),
  e("10.82Z", "Fabrication de cacao, chocolat et de produits de confiserie", "C", C),
  e("10.83Z", "Transformation du thé et du café", "C", C),
  e("10.84Z", "Fabrication de condiments et assaisonnements", "C", C),
  e("10.85Z", "Fabrication de plats préparés", "C", C),
  e("10.86Z", "Fabrication d'aliments homogénéisés et diététiques", "C", C),
  e("10.89Z", "Fabrication d'autres produits alimentaires n.c.a.", "C", C),
  e("10.91Z", "Fabrication d'aliments pour animaux de ferme", "C", C),
  e("10.92Z", "Fabrication d'aliments pour animaux de compagnie", "C", C),
  e("11.01Z", "Production de boissons alcooliques distillées", "C", C),
  e("11.02A", "Fabrication de vins effervescents", "C", C),
  e("11.02B", "Vinification", "C", C),
  e("11.03Z", "Fabrication de cidre et de vins de fruits", "C", C),
  e("11.04Z", "Production d'autres boissons fermentées non distillées", "C", C),
  e("11.05Z", "Fabrication de bière", "C", C),
  e("11.06Z", "Fabrication de malt", "C", C),
  e("11.07A", "Industrie des eaux de table", "C", C),
  e("11.07B", "Production de boissons rafraîchissantes", "C", C),
  e("12.00Z", "Fabrication de produits à base de tabac", "C", C),
  e("13.10Z", "Préparation de fibres textiles et filature", "C", C),
  e("13.20Z", "Tissage", "C", C),
  e("13.30Z", "Ennoblissement textile", "C", C),
  e("13.91Z", "Fabrication d'étoffes à mailles", "C", C),
  e("13.92Z", "Fabrication d'articles textiles, sauf habillement", "C", C),
  e("13.93Z", "Fabrication de tapis et moquettes", "C", C),
  e("13.94Z", "Fabrication de ficelles, cordes, cordages, filets", "C", C),
  e("13.95Z", "Fabrication de non-tissés, sauf habillement", "C", C),
  e("13.96Z", "Fabrication d'autres textiles techniques et industriels", "C", C),
  e("13.99Z", "Fabrication d'autres textiles n.c.a.", "C", C),
  e("14.11Z", "Fabrication de vêtements en cuir", "C", C),
  e("14.12Z", "Fabrication de vêtements de travail", "C", C),
  e("14.13Z", "Fabrication de vêtements de dessus", "C", C),
  e("14.14Z", "Fabrication de vêtements de dessous", "C", C),
  e("14.19Z", "Fabrication d'autres vêtements et accessoires", "C", C),
  e("14.20Z", "Fabrication d'articles en fourrure", "C", C),
  e("14.31Z", "Fabrication d'articles chaussants à mailles", "C", C),
  e("14.39Z", "Fabrication d'autres articles à mailles", "C", C),
  e("15.11Z", "Apprêt et tannage des cuirs ; préparation et teinture des fourrures", "C", C),
  e("15.12Z", "Fabrication d'articles de voyage, de maroquinerie et de sellerie", "C", C),
  e("15.20Z", "Fabrication de chaussures", "C", C),
  e("16.10A", "Sciage et rabotage du bois, sauf imprégnation", "C", C),
  e("16.10B", "Imprégnation du bois", "C", C),
  e("16.21Z", "Fabrication de placage et de panneaux de bois", "C", C),
  e("16.22Z", "Fabrication de parquets assemblés", "C", C),
  e("16.23Z", "Fabrication de charpentes et d'autres menuiseries", "C", C),
  e("16.24Z", "Fabrication d'emballages en bois", "C", C),
  e("16.29Z", "Fabrication d'autres objets en bois, en liège, vannerie et sparterie", "C", C),
  e("17.11Z", "Fabrication de pâte à papier", "C", C),
  e("17.12Z", "Fabrication de papier et de carton", "C", C),
  e("17.21A", "Fabrication de carton ondulé", "C", C),
  e("17.21B", "Fabrication de cartonnages", "C", C),
  e("17.21C", "Fabrication d'emballages en papier", "C", C),
  e("17.22Z", "Fabrication d'articles en papier à usage sanitaire ou domestique", "C", C),
  e("17.23Z", "Fabrication d'articles de papeterie", "C", C),
  e("17.24Z", "Fabrication de papiers peints", "C", C),
  e("17.29Z", "Fabrication d'autres articles en papier ou en carton", "C", C),
  e("18.11Z", "Imprimerie de journaux", "C", C),
  e("18.12Z", "Autre imprimerie (labeur)", "C", C),
  e("18.13Z", "Activités de pré-presse", "C", C),
  e("18.14Z", "Reliure et activités connexes", "C", C),
  e("18.20Z", "Reproduction d'enregistrements", "C", C),
  e("19.10Z", "Cokéfaction", "C", C),
  e("19.20Z", "Raffinage du pétrole", "C", C),
  e("20.11Z", "Fabrication de gaz industriels", "C", C),
  e("20.12Z", "Fabrication de colorants et de pigments", "C", C),
  e("20.13A", "Enrichissement et retraitement de matières nucléaires", "C", C),
  e("20.13B", "Fabrication d'autres produits chimiques inorganiques de base n.c.a.", "C", C),
  e("20.14Z", "Fabrication d'autres produits chimiques organiques de base", "C", C),
  e("20.15Z", "Fabrication de produits azotés et d'engrais", "C", C),
  e("20.16Z", "Fabrication de matières plastiques de base", "C", C),
  e("20.17Z", "Fabrication de caoutchouc synthétique", "C", C),
  e("20.20Z", "Fabrication de pesticides et d'autres produits agrochimiques", "C", C),
  e("20.30Z", "Fabrication de peintures, vernis, encres et mastics", "C", C),
  e("20.41Z", "Fabrication de savons, détergents et produits d'entretien", "C", C),
  e("20.42Z", "Fabrication de parfums et de produits pour la toilette", "C", C),
  e("20.51Z", "Fabrication de produits explosifs", "C", C),
  e("20.52Z", "Fabrication de colles", "C", C),
  e("20.53Z", "Fabrication d'huiles essentielles", "C", C),
  e("20.59Z", "Fabrication d'autres produits chimiques n.c.a.", "C", C),
  e("20.60Z", "Fabrication de fibres artificielles ou synthétiques", "C", C),
  e("21.10Z", "Fabrication de produits pharmaceutiques de base", "C", C),
  e("21.20Z", "Fabrication de préparations pharmaceutiques", "C", C),
  e("22.11Z", "Fabrication et rechapage de pneumatiques", "C", C),
  e("22.19Z", "Fabrication d'autres articles en caoutchouc", "C", C),
  e("22.21Z", "Fabrication de plaques, feuilles, tubes et profilés en matières plastiques", "C", C),
  e("22.22Z", "Fabrication d'emballages en matières plastiques", "C", C),
  e("22.23Z", "Fabrication d'éléments en matières plastiques pour la construction", "C", C),
  e("22.29A", "Fabrication de pièces techniques en matières plastiques", "C", C),
  e("22.29B", "Fabrication de produits de consommation courante en matières plastiques", "C", C),
  e("23.11Z", "Fabrication de verre plat", "C", C),
  e("23.12Z", "Façonnage et transformation du verre plat", "C", C),
  e("23.13Z", "Fabrication de verre creux", "C", C),
  e("23.14Z", "Fabrication de fibres de verre", "C", C),
  e("23.19Z", "Fabrication et façonnage d'autres articles en verre", "C", C),
  e("23.20Z", "Fabrication de produits réfractaires", "C", C),
  e("23.31Z", "Fabrication de carreaux en céramique", "C", C),
  e("23.32Z", "Fabrication de briques, tuiles et produits de construction en terres cuites", "C", C),
  e("23.41Z", "Fabrication d'articles céramiques à usage domestique ou ornemental", "C", C),
  e("23.42Z", "Fabrication d'appareils sanitaires en céramique", "C", C),
  e("23.43Z", "Fabrication d'isolateurs et pièces isolantes en céramique", "C", C),
  e("23.44Z", "Fabrication d'autres produits céramiques à usage technique", "C", C),
  e("23.49Z", "Fabrication d'autres produits céramiques", "C", C),
  e("23.51Z", "Fabrication de ciment", "C", C),
  e("23.52Z", "Fabrication de chaux et plâtre", "C", C),
  e("23.61Z", "Fabrication de produits en béton pour la construction", "C", C),
  e("23.62Z", "Fabrication de produits en plâtre pour la construction", "C", C),
  e("23.63Z", "Fabrication de béton prêt à l'emploi", "C", C),
  e("23.64Z", "Fabrication de mortiers et bétons secs", "C", C),
  e("23.65Z", "Fabrication d'ouvrages en fibre-ciment", "C", C),
  e("23.69Z", "Fabrication d'autres ouvrages en béton, en ciment ou en plâtre", "C", C),
  e("23.70Z", "Taille, façonnage et finissage de pierres ornementales et de construction", "C", C),
  e("23.91Z", "Fabrication de produits abrasifs", "C", C),
  e("23.99Z", "Fabrication d'autres produits minéraux non métalliques n.c.a.", "C", C),
  e("24.10Z", "Sidérurgie", "C", C),
  e("24.20Z", "Fabrication de tubes, tuyaux, profilés creux et accessoires en acier", "C", C),
  e("24.31Z", "Étirage à froid de barres", "C", C),
  e("24.32Z", "Laminage à froid de feuillards", "C", C),
  e("24.33Z", "Profilage à froid par formage ou pliage", "C", C),
  e("24.34Z", "Tréfilage à froid", "C", C),
  e("24.41Z", "Production de métaux précieux", "C", C),
  e("24.42Z", "Métallurgie de l'aluminium", "C", C),
  e("24.43Z", "Métallurgie du plomb, du zinc ou de l'étain", "C", C),
  e("24.44Z", "Métallurgie du cuivre", "C", C),
  e("24.45Z", "Métallurgie des autres métaux non ferreux", "C", C),
  e("24.46Z", "Élaboration et transformation de matières nucléaires", "C", C),
  e("24.51Z", "Fonderie de fonte", "C", C),
  e("24.52Z", "Fonderie d'acier", "C", C),
  e("24.53Z", "Fonderie de métaux légers", "C", C),
  e("24.54Z", "Fonderie d'autres métaux non ferreux", "C", C),
  e("25.11Z", "Fabrication de structures métalliques et de parties de structures", "C", C),
  e("25.12Z", "Fabrication de portes et fenêtres en métal", "C", C),
  e("25.21Z", "Fabrication de radiateurs et de chaudières pour le chauffage central", "C", C),
  e("25.29Z", "Fabrication d'autres réservoirs, citernes et conteneurs métalliques", "C", C),
  e("25.30Z", "Fabrication de générateurs de vapeur, à l'exception des chaudières pour le chauffage central", "C", C),
  e("25.40Z", "Fabrication d'armes et de munitions", "C", C),
  e("25.50A", "Forge, estampage, matriçage ; métallurgie des poudres", "C", C),
  e("25.50B", "Découpage, emboutissage", "C", C),
  e("25.61Z", "Traitement et revêtement des métaux", "C", C),
  e("25.62A", "Décolletage", "C", C),
  e("25.62B", "Mécanique industrielle", "C", C),
  e("25.71Z", "Fabrication de coutellerie", "C", C),
  e("25.72Z", "Fabrication de serrures et de ferrures", "C", C),
  e("25.73A", "Fabrication de moules et modèles", "C", C),
  e("25.73B", "Fabrication d'autres outillages", "C", C),
  e("25.91Z", "Fabrication de fûts et emballages métalliques similaires", "C", C),
  e("25.92Z", "Fabrication d'emballages métalliques légers", "C", C),
  e("25.93Z", "Fabrication d'articles en fils métalliques, de chaînes et de ressorts", "C", C),
  e("25.94Z", "Fabrication de vis et de boulons", "C", C),
  e("25.99A", "Fabrication d'articles métalliques ménagers", "C", C),
  e("25.99B", "Fabrication d'autres articles métalliques", "C", C),
  e("26.11Z", "Fabrication de composants électroniques", "C", C),
  e("26.12Z", "Fabrication de cartes électroniques assemblées", "C", C),
  e("26.20Z", "Fabrication d'ordinateurs et d'équipements périphériques", "C", C),
  e("26.30Z", "Fabrication d'équipements de communication", "C", C),
  e("26.40Z", "Fabrication de produits électroniques grand public", "C", C),
  e("26.51A", "Fabrication d'équipements d'aide à la navigation", "C", C),
  e("26.51B", "Fabrication d'instrumentation scientifique et technique", "C", C),
  e("26.52Z", "Horlogerie", "C", C),
  e("26.60Z", "Fabrication d'équipements d'irradiation médicale, d'équipements électromédicaux", "C", C),
  e("26.70Z", "Fabrication de matériels optique et photographique", "C", C),
  e("26.80Z", "Fabrication de supports magnétiques et optiques", "C", C),
  e("27.11Z", "Fabrication de moteurs, génératrices et transformateurs électriques", "C", C),
  e("27.12Z", "Fabrication de matériel de distribution et de commande électrique", "C", C),
  e("27.20Z", "Fabrication de piles et d'accumulateurs électriques", "C", C),
  e("27.31Z", "Fabrication de câbles de fibres optiques", "C", C),
  e("27.32Z", "Fabrication d'autres fils et câbles électroniques ou électriques", "C", C),
  e("27.33Z", "Fabrication de matériel d'installation électrique", "C", C),
  e("27.40Z", "Fabrication d'appareils d'éclairage électrique", "C", C),
  e("27.51Z", "Fabrication d'appareils électroménagers", "C", C),
  e("27.52Z", "Fabrication d'appareils ménagers non électriques", "C", C),
  e("27.90Z", "Fabrication d'autres matériels électriques", "C", C),
  e("28.11Z", "Fabrication de moteurs et turbines, à l'exception des moteurs d'avions et de véhicules", "C", C),
  e("28.12Z", "Fabrication d'équipements hydrauliques et pneumatiques", "C", C),
  e("28.13Z", "Fabrication d'autres pompes et compresseurs", "C", C),
  e("28.14Z", "Fabrication d'autres articles de robinetterie", "C", C),
  e("28.15Z", "Fabrication d'engrenages et d'organes mécaniques de transmission", "C", C),
  e("28.21Z", "Fabrication de fours et brûleurs", "C", C),
  e("28.22Z", "Fabrication de matériels de levage et de manutention", "C", C),
  e("28.23Z", "Fabrication de machines et d'équipements de bureau (hors ordinateurs)", "C", C),
  e("28.24Z", "Fabrication d'outillage à main motorisé", "C", C),
  e("28.25Z", "Fabrication d'équipements aérauliques et frigorifiques industriels", "C", C),
  e("28.29A", "Fabrication d'équipements d'emballage, de conditionnement et de pesage", "C", C),
  e("28.29B", "Fabrication d'autres machines d'usage général", "C", C),
  e("28.30Z", "Fabrication de machines agricoles et forestières", "C", C),
  e("28.41Z", "Fabrication de machines-outils pour le travail des métaux", "C", C),
  e("28.49Z", "Fabrication d'autres machines-outils", "C", C),
  e("28.91Z", "Fabrication de machines pour la métallurgie", "C", C),
  e("28.92Z", "Fabrication de machines pour l'extraction ou la construction", "C", C),
  e("28.93Z", "Fabrication de machines pour l'industrie alimentaire, des boissons et du tabac", "C", C),
  e("28.94Z", "Fabrication de machines pour les industries textiles, l'habillement et le cuir", "C", C),
  e("28.95Z", "Fabrication de machines pour les industries du papier et du carton", "C", C),
  e("28.96Z", "Fabrication de machines pour le travail du caoutchouc ou des matières plastiques", "C", C),
  e("28.99A", "Fabrication de machines d'imprimerie", "C", C),
  e("28.99B", "Fabrication d'autres machines spécialisées", "C", C),
  e("29.10Z", "Construction de véhicules automobiles", "C", C),
  e("29.20Z", "Fabrication de carrosseries et remorques", "C", C),
  e("29.31Z", "Fabrication d'équipements électriques et électroniques automobiles", "C", C),
  e("29.32Z", "Fabrication d'autres équipements automobiles", "C", C),
  e("30.11Z", "Construction de navires et de structures flottantes", "C", C),
  e("30.12Z", "Construction de bateaux de plaisance", "C", C),
  e("30.20Z", "Construction de locomotives et d'autre matériel ferroviaire roulant", "C", C),
  e("30.30Z", "Construction aéronautique et spatiale", "C", C),
  e("30.40Z", "Construction de véhicules militaires de combat", "C", C),
  e("30.91Z", "Fabrication de motocycles", "C", C),
  e("30.92Z", "Fabrication de bicyclettes et de véhicules pour invalides", "C", C),
  e("30.99Z", "Fabrication d'autres équipements de transport n.c.a.", "C", C),
  e("31.01Z", "Fabrication de meubles de bureau et de magasin", "C", C),
  e("31.02Z", "Fabrication de meubles de cuisine", "C", C),
  e("31.03Z", "Fabrication de matelas", "C", C),
  e("31.09A", "Fabrication de sièges d'ameublement d'intérieur", "C", C),
  e("31.09B", "Fabrication d'autres meubles et industries connexes de l'ameublement", "C", C),
  e("32.11Z", "Frappe de monnaies", "C", C),
  e("32.12Z", "Fabrication d'articles de joaillerie et bijouterie", "C", C),
  e("32.13Z", "Fabrication d'articles de bijouterie fantaisie et articles similaires", "C", C),
  e("32.20Z", "Fabrication d'instruments de musique", "C", C),
  e("32.30Z", "Fabrication d'articles de sport", "C", C),
  e("32.40Z", "Fabrication de jeux et jouets", "C", C),
  e("32.50A", "Fabrication de matériel médicochirurgical et dentaire", "C", C),
  e("32.50B", "Fabrication de lunettes", "C", C),
  e("32.91Z", "Fabrication d'articles de brosserie", "C", C),
  e("32.99Z", "Autres activités manufacturières n.c.a.", "C", C),
  e("33.11Z", "Réparation d'ouvrages en métaux", "C", C),
  e("33.12Z", "Réparation de machines et équipements mécaniques", "C", C),
  e("33.13Z", "Réparation de matériels électroniques et optiques", "C", C),
  e("33.14Z", "Réparation d'équipements électriques", "C", C),
  e("33.15Z", "Réparation et maintenance navale", "C", C),
  e("33.16Z", "Réparation et maintenance d'aéronefs et d'engins spatiaux", "C", C),
  e("33.17Z", "Réparation et maintenance d'autres équipements de transport", "C", C),
  e("33.19Z", "Réparation d'autres équipements", "C", C),
  e("33.20A", "Installation de structures métalliques, chaudronnées et de tuyauterie", "C", C),
  e("33.20B", "Installation de machines et équipements mécaniques", "C", C),
  e("33.20C", "Conception d'ensemble et assemblage sur site industriel d'équipements de contrôle des processus industriels", "C", C),
  e("33.20D", "Installation d'équipements électriques et électroniques", "C", C),

  // ── D — Énergie ───────────────────────────────────────────────────
  e("35.11Z", "Production d'électricité", "D", D),
  e("35.12Z", "Transport d'électricité", "D", D),
  e("35.13Z", "Distribution d'électricité", "D", D),
  e("35.14Z", "Commerce d'électricité", "D", D),
  e("35.21Z", "Production de combustibles gazeux", "D", D),
  e("35.22Z", "Distribution de combustibles gazeux par conduites", "D", D),
  e("35.23Z", "Commerce de combustibles gazeux par conduites", "D", D),
  e("35.30Z", "Production et distribution de vapeur et d'air conditionné", "D", D),

  // ── E — Eau et déchets ────────────────────────────────────────────
  e("36.00Z", "Captage, traitement et distribution d'eau", "E", E),
  e("37.00Z", "Collecte et traitement des eaux usées", "E", E),
  e("38.11Z", "Collecte des déchets non dangereux", "E", E),
  e("38.12Z", "Collecte des déchets dangereux", "E", E),
  e("38.21Z", "Traitement et élimination des déchets non dangereux", "E", E),
  e("38.22Z", "Traitement et élimination des déchets dangereux", "E", E),
  e("38.31Z", "Démantèlement d'épaves", "E", E),
  e("38.32Z", "Récupération de déchets triés", "E", E),
  e("39.00Z", "Dépollution et autres services de gestion des déchets", "E", E),

  // ── F — Construction ──────────────────────────────────────────────
  e("41.10A", "Promotion immobilière de logements", "F", F),
  e("41.10B", "Promotion immobilière de bureaux", "F", F),
  e("41.10C", "Promotion immobilière d'autres bâtiments", "F", F),
  e("41.10D", "Supports juridiques de programmes", "F", F),
  e("41.20A", "Construction de maisons individuelles", "F", F),
  e("41.20B", "Construction d'autres bâtiments", "F", F),
  e("42.11Z", "Construction de routes et autoroutes", "F", F),
  e("42.12Z", "Construction de voies ferrées de surface et souterraines", "F", F),
  e("42.13A", "Construction d'ouvrages d'art", "F", F),
  e("42.13B", "Construction et entretien de tunnels", "F", F),
  e("42.21Z", "Construction de réseaux pour fluides", "F", F),
  e("42.22Z", "Construction de réseaux électriques et de télécommunications", "F", F),
  e("42.91Z", "Construction d'ouvrages maritimes et fluviaux", "F", F),
  e("42.99Z", "Construction d'autres ouvrages de génie civil n.c.a.", "F", F),
  e("43.11Z", "Travaux de démolition", "F", F),
  e("43.12A", "Travaux de terrassement courants et travaux préparatoires", "F", F),
  e("43.12B", "Travaux de drainage agricole", "F", F),
  e("43.13Z", "Forages et sondages", "F", F),
  e("43.21A", "Travaux d'installation électrique dans tous locaux", "F", F),
  e("43.21B", "Travaux d'installation électrique sur la voie publique", "F", F),
  e("43.22A", "Travaux d'installation d'eau et de gaz en tous locaux", "F", F),
  e("43.22B", "Travaux d'installation d'équipements thermiques et de climatisation", "F", F),
  e("43.29A", "Travaux d'isolation", "F", F),
  e("43.29B", "Autres travaux d'installation n.c.a.", "F", F),
  e("43.31Z", "Travaux de plâtrerie", "F", F),
  e("43.32A", "Travaux de menuiserie bois et PVC", "F", F),
  e("43.32B", "Travaux de menuiserie métallique et serrurerie", "F", F),
  e("43.32C", "Agencement de lieux de vente", "F", F),
  e("43.33Z", "Travaux de revêtement des sols et des murs", "F", F),
  e("43.34Z", "Travaux de peinture et vitrerie", "F", F),
  e("43.39Z", "Autres travaux de finition", "F", F),
  e("43.91A", "Travaux de charpente", "F", F),
  e("43.91B", "Travaux de couverture par éléments", "F", F),
  e("43.99A", "Travaux d'étanchéification", "F", F),
  e("43.99B", "Travaux de montage de structures métalliques", "F", F),
  e("43.99C", "Travaux de maçonnerie générale et gros œuvre de bâtiment", "F", F),
  e("43.99D", "Autres travaux spécialisés de construction", "F", F),
  e("43.99E", "Location avec opérateur de matériel de construction", "F", F),

  // ── G — Commerce ──────────────────────────────────────────────────
  e("45.11Z", "Commerce de voitures et de véhicules automobiles légers", "G", G),
  e("45.19Z", "Commerce d'autres véhicules automobiles", "G", G),
  e("45.20A", "Entretien et réparation de véhicules automobiles légers", "G", G),
  e("45.20B", "Entretien et réparation d'autres véhicules automobiles", "G", G),
  e("45.31Z", "Commerce de gros d'équipements automobiles", "G", G),
  e("45.32Z", "Commerce de détail d'équipements automobiles", "G", G),
  e("45.40Z", "Commerce et réparation de motocycles", "G", G),
  e("46.11Z", "Intermédiaires du commerce en matières premières agricoles, animaux vivants, matières premières textiles", "G", G),
  e("46.12A", "Centrales d'achat de carburant", "G", G),
  e("46.12B", "Autres intermédiaires du commerce en combustibles, métaux, minéraux et produits chimiques", "G", G),
  e("46.13Z", "Intermédiaires du commerce en bois et matériaux de construction", "G", G),
  e("46.14Z", "Intermédiaires du commerce en machines, équipements industriels, navires et avions", "G", G),
  e("46.15Z", "Intermédiaires du commerce en meubles, articles de ménage et quincaillerie", "G", G),
  e("46.16Z", "Intermédiaires du commerce en textiles, habillement, fourrures, chaussures et articles en cuir", "G", G),
  e("46.17A", "Centrales d'achat alimentaires", "G", G),
  e("46.17B", "Autres intermédiaires du commerce en denrées, boissons et tabac", "G", G),
  e("46.18Z", "Intermédiaires spécialisés dans le commerce d'autres produits spécifiques", "G", G),
  e("46.19A", "Centrales d'achat non alimentaires", "G", G),
  e("46.19B", "Autres intermédiaires du commerce en produits divers", "G", G),
  e("46.21Z", "Commerce de gros de céréales, de tabac non manufacturé, de semences et d'aliments pour le bétail", "G", G),
  e("46.22Z", "Commerce de gros de fleurs et plantes", "G", G),
  e("46.23Z", "Commerce de gros d'animaux vivants", "G", G),
  e("46.24Z", "Commerce de gros de cuirs et peaux", "G", G),
  e("46.31Z", "Commerce de gros de fruits et légumes", "G", G),
  e("46.32A", "Commerce de gros de viandes de boucherie", "G", G),
  e("46.32B", "Commerce de gros de produits à base de viande", "G", G),
  e("46.32C", "Commerce de gros de volailles et gibiers", "G", G),
  e("46.33Z", "Commerce de gros de produits laitiers, œufs, huiles et matières grasses comestibles", "G", G),
  e("46.34Z", "Commerce de gros de boissons", "G", G),
  e("46.35Z", "Commerce de gros de produits à base de tabac", "G", G),
  e("46.36Z", "Commerce de gros de sucre, chocolat et confiserie", "G", G),
  e("46.37Z", "Commerce de gros de café, thé, cacao et épices", "G", G),
  e("46.38A", "Commerce de gros de poissons, crustacés et mollusques", "G", G),
  e("46.38B", "Commerce de gros alimentaire spécialisé divers", "G", G),
  e("46.39A", "Commerce de gros de produits alimentaires non spécialisés à prédominance de produits frais", "G", G),
  e("46.39B", "Commerce de gros de produits surgelés", "G", G),
  e("46.41Z", "Commerce de gros de textiles", "G", G),
  e("46.42Z", "Commerce de gros d'habillement et de chaussures", "G", G),
  e("46.43Z", "Commerce de gros d'appareils électroménagers", "G", G),
  e("46.44Z", "Commerce de gros de vaisselle, verrerie et produits d'entretien", "G", G),
  e("46.45Z", "Commerce de gros de parfumerie et de produits de beauté", "G", G),
  e("46.46Z", "Commerce de gros de produits pharmaceutiques", "G", G),
  e("46.47Z", "Commerce de gros de meubles, de tapis et d'appareils d'éclairage", "G", G),
  e("46.48Z", "Commerce de gros d'articles d'horlogerie et de bijouterie", "G", G),
  e("46.49Z", "Commerce de gros d'autres biens domestiques", "G", G),
  e("46.51Z", "Commerce de gros d'ordinateurs, d'équipements informatiques périphériques et de logiciels", "G", G),
  e("46.52Z", "Commerce de gros de composants et d'équipements électroniques et de télécommunication", "G", G),
  e("46.61Z", "Commerce de gros de matériel agricole", "G", G),
  e("46.62Z", "Commerce de gros de machines-outils", "G", G),
  e("46.63Z", "Commerce de gros de machines pour l'extraction, la construction et le génie civil", "G", G),
  e("46.64Z", "Commerce de gros de machines pour l'industrie textile et l'habillement", "G", G),
  e("46.65Z", "Commerce de gros de mobilier de bureau", "G", G),
  e("46.66Z", "Commerce de gros d'autres machines et équipements de bureau", "G", G),
  e("46.69A", "Commerce de gros de matériel électrique", "G", G),
  e("46.69B", "Commerce de gros de fournitures et équipements industriels divers", "G", G),
  e("46.71Z", "Commerce de gros de combustibles et de produits annexes", "G", G),
  e("46.72Z", "Commerce de gros de minerais et métaux", "G", G),
  e("46.73A", "Commerce de gros de bois et de matériaux de construction", "G", G),
  e("46.73B", "Commerce de gros d'appareils sanitaires et de produits de décoration", "G", G),
  e("46.74A", "Commerce de gros de quincaillerie", "G", G),
  e("46.74B", "Commerce de gros de fournitures pour la plomberie et le chauffage", "G", G),
  e("46.75Z", "Commerce de gros de produits chimiques", "G", G),
  e("46.76Z", "Commerce de gros d'autres produits intermédiaires", "G", G),
  e("46.77Z", "Commerce de gros de déchets et débris", "G", G),
  e("47.11A", "Commerce de détail de produits surgelés", "G", G),
  e("47.11B", "Commerce d'alimentation générale", "G", G),
  e("47.11C", "Supérettes", "G", G),
  e("47.11D", "Supermarchés", "G", G),
  e("47.11E", "Magasins multi-commerces", "G", G),
  e("47.11F", "Hypermarchés", "G", G),
  e("47.19A", "Grands magasins", "G", G),
  e("47.19B", "Autres commerces de détail en magasin non spécialisé", "G", G),
  e("47.21Z", "Commerce de détail de fruits et légumes en magasin spécialisé", "G", G),
  e("47.22Z", "Commerce de détail de viandes et de produits à base de viande", "G", G),
  e("47.23Z", "Commerce de détail de poissons, crustacés et mollusques", "G", G),
  e("47.24Z", "Commerce de détail de pain, pâtisserie et confiserie", "G", G),
  e("47.25Z", "Commerce de détail de boissons en magasin spécialisé", "G", G),
  e("47.26Z", "Commerce de détail de produits à base de tabac", "G", G),
  e("47.29Z", "Autres commerces de détail alimentaires en magasin spécialisé", "G", G),
  e("47.30Z", "Commerce de détail de carburants en magasin spécialisé", "G", G),
  e("47.41Z", "Commerce de détail d'ordinateurs, d'unités périphériques et de logiciels", "G", G),
  e("47.42Z", "Commerce de détail de matériels de télécommunication", "G", G),
  e("47.43Z", "Commerce de détail de matériels audio/vidéo", "G", G),
  e("47.51Z", "Commerce de détail de textiles en magasin spécialisé", "G", G),
  e("47.52A", "Commerce de détail de quincaillerie, peintures et verres (petites surfaces)", "G", G),
  e("47.52B", "Commerce de détail de quincaillerie, peintures et verres (grandes surfaces)", "G", G),
  e("47.53Z", "Commerce de détail de tapis, moquettes et revêtements de murs et de sols", "G", G),
  e("47.54Z", "Commerce de détail d'appareils électroménagers en magasin spécialisé", "G", G),
  e("47.59A", "Commerce de détail de meubles", "G", G),
  e("47.59B", "Commerce de détail d'autres équipements du foyer", "G", G),
  e("47.61Z", "Commerce de détail de livres en magasin spécialisé", "G", G),
  e("47.62Z", "Commerce de détail de journaux et papeterie", "G", G),
  e("47.63Z", "Commerce de détail d'enregistrements musicaux et vidéo", "G", G),
  e("47.64Z", "Commerce de détail d'articles de sport en magasin spécialisé", "G", G),
  e("47.65Z", "Commerce de détail de jeux et jouets en magasin spécialisé", "G", G),
  e("47.71Z", "Commerce de détail d'habillement en magasin spécialisé", "G", G),
  e("47.72A", "Commerce de détail de la chaussure", "G", G),
  e("47.72B", "Commerce de détail de maroquinerie et d'articles de voyage", "G", G),
  e("47.73Z", "Commerce de détail de produits pharmaceutiques en magasin spécialisé", "G", G),
  e("47.74Z", "Commerce de détail d'articles médicaux et orthopédiques", "G", G),
  e("47.75Z", "Commerce de détail de parfumerie et de produits de beauté", "G", G),
  e("47.76Z", "Commerce de détail de fleurs, plantes, graines, engrais, animaux de compagnie", "G", G),
  e("47.77Z", "Commerce de détail d'articles d'horlogerie et de bijouterie", "G", G),
  e("47.78A", "Commerce de détail d'optique", "G", G),
  e("47.78B", "Commerce de détail de charbons et combustibles", "G", G),
  e("47.78C", "Autres commerces de détail spécialisés divers", "G", G),
  e("47.79Z", "Commerce de détail de biens d'occasion en magasin", "G", G),
  e("47.81Z", "Commerce de détail alimentaire sur éventaires et marchés", "G", G),
  e("47.82Z", "Commerce de détail de textiles, habillement et chaussures sur éventaires et marchés", "G", G),
  e("47.89Z", "Autres commerces de détail sur éventaires et marchés", "G", G),
  e("47.91A", "Vente à distance sur catalogue général", "G", G),
  e("47.91B", "Vente à distance sur catalogue spécialisé", "G", G),
  e("47.99A", "Vente à domicile", "G", G),
  e("47.99B", "Vente par automates et autres commerces de détail hors magasin n.c.a.", "G", G),

  // ── H — Transports et entreposage ─────────────────────────────────
  e("49.10Z", "Transport ferroviaire interurbain de voyageurs", "H", H),
  e("49.20Z", "Transports ferroviaires de fret", "H", H),
  e("49.31Z", "Transports urbains et suburbains de voyageurs", "H", H),
  e("49.32Z", "Transports de voyageurs par taxis", "H", H),
  e("49.39A", "Transports routiers réguliers de voyageurs", "H", H),
  e("49.39B", "Autres transports routiers de voyageurs", "H", H),
  e("49.39C", "Téléphériques et remontées mécaniques", "H", H),
  e("49.41A", "Transports routiers de fret interurbains", "H", H),
  e("49.41B", "Transports routiers de fret de proximité", "H", H),
  e("49.41C", "Location de camions avec chauffeur", "H", H),
  e("49.42Z", "Services de déménagement", "H", H),
  e("49.50Z", "Transports par conduites", "H", H),
  e("50.10Z", "Transports maritimes et côtiers de passagers", "H", H),
  e("50.20Z", "Transports maritimes et côtiers de fret", "H", H),
  e("50.30Z", "Transports fluviaux de passagers", "H", H),
  e("50.40Z", "Transports fluviaux de fret", "H", H),
  e("51.10Z", "Transports aériens de passagers", "H", H),
  e("51.21Z", "Transports aériens de fret", "H", H),
  e("51.22Z", "Transports spatiaux", "H", H),
  e("52.10A", "Entreposage et stockage frigorifique", "H", H),
  e("52.10B", "Entreposage et stockage non frigorifique", "H", H),
  e("52.21Z", "Services auxiliaires des transports terrestres", "H", H),
  e("52.22Z", "Services auxiliaires des transports par eau", "H", H),
  e("52.23Z", "Services auxiliaires des transports aériens", "H", H),
  e("52.24A", "Manutention portuaire", "H", H),
  e("52.24B", "Manutention non portuaire", "H", H),
  e("52.29A", "Messagerie, fret express", "H", H),
  e("52.29B", "Affrètement et organisation des transports", "H", H),
  e("53.10Z", "Activités de poste dans le cadre d'une obligation de service universel", "H", H),
  e("53.20Z", "Autres activités de poste et de courrier", "H", H),

  // ── I — Hébergement et restauration ──────────────────────────────
  e("55.10Z", "Hôtels et hébergement similaire", "I", I),
  e("55.20Z", "Hébergement touristique et autre hébergement de courte durée", "I", I),
  e("55.30Z", "Terrains de camping et parcs pour caravanes ou véhicules de loisirs", "I", I),
  e("55.90Z", "Autres hébergements", "I", I),
  e("56.10A", "Restauration traditionnelle", "I", I),
  e("56.10B", "Cafétérias et autres libres-services", "I", I),
  e("56.10C", "Restauration rapide", "I", I),
  e("56.21Z", "Services des traiteurs", "I", I),
  e("56.29A", "Restauration collective sous contrat", "I", I),
  e("56.29B", "Autres services de restauration n.c.a.", "I", I),
  e("56.30Z", "Débits de boissons", "I", I),

  // ── J — Information et communication ─────────────────────────────
  e("58.11Z", "Édition de livres", "J", J),
  e("58.12Z", "Édition de répertoires et de fichiers d'adresses", "J", J),
  e("58.13Z", "Édition de journaux", "J", J),
  e("58.14Z", "Édition de revues et périodiques", "J", J),
  e("58.19Z", "Autres activités d'édition", "J", J),
  e("58.21Z", "Édition de jeux électroniques", "J", J),
  e("58.29A", "Édition de logiciels système et de réseau", "J", J),
  e("58.29B", "Édition de logiciels outils de développement et de langages", "J", J),
  e("58.29C", "Édition de logiciels applicatifs", "J", J),
  e("59.11A", "Production de films et de programmes pour la télévision", "J", J),
  e("59.11B", "Production de films institutionnels et publicitaires", "J", J),
  e("59.11C", "Production de films pour le cinéma", "J", J),
  e("59.12Z", "Post-production de films cinématographiques, de vidéo et de programmes de télévision", "J", J),
  e("59.13A", "Distribution de films cinématographiques", "J", J),
  e("59.13B", "Édition et distribution vidéo", "J", J),
  e("59.14Z", "Projection de films cinématographiques", "J", J),
  e("59.20Z", "Enregistrement sonore et édition musicale", "J", J),
  e("60.10Z", "Édition et diffusion de programmes radio", "J", J),
  e("60.20A", "Édition de chaînes généralistes", "J", J),
  e("60.20B", "Édition de chaînes thématiques", "J", J),
  e("61.10Z", "Télécommunications filaires", "J", J),
  e("61.20Z", "Télécommunications sans fil", "J", J),
  e("61.30Z", "Télécommunications par satellite", "J", J),
  e("61.90Z", "Autres activités de télécommunication", "J", J),
  e("62.01Z", "Programmation informatique", "J", J),
  e("62.02A", "Conseil en systèmes et logiciels informatiques", "J", J),
  e("62.02B", "Tierce maintenance de systèmes et d'applications informatiques", "J", J),
  e("62.03Z", "Gestion d'installations informatiques", "J", J),
  e("62.09Z", "Autres activités informatiques", "J", J),
  e("63.11Z", "Traitement de données, hébergement et activités connexes (cloud, data centers)", "J", J),
  e("63.12Z", "Portails Internet", "J", J),
  e("63.91Z", "Activités des agences de presse", "J", J),
  e("63.99Z", "Autres services d'information n.c.a.", "J", J),

  // ── K — Finance et assurance ─────────────────────────────────────
  e("64.11Z", "Activités de banque centrale", "K", K),
  e("64.19Z", "Autres intermédiations monétaires (banques)", "K", K),
  e("64.20Z", "Activités des sociétés holding", "K", K),
  e("64.30Z", "Fonds de placement et entités financières similaires", "K", K),
  e("64.91Z", "Crédit-bail", "K", K),
  e("64.92Z", "Autre distribution de crédit", "K", K),
  e("64.99Z", "Autres activités des services financiers n.c.a.", "K", K),
  e("65.11Z", "Assurance vie", "K", K),
  e("65.12Z", "Autres assurances (dommages, responsabilité…)", "K", K),
  e("65.20Z", "Réassurance", "K", K),
  e("65.30Z", "Caisses de retraite", "K", K),
  e("66.11Z", "Administration de marchés financiers", "K", K),
  e("66.12Z", "Courtage de valeurs mobilières et de marchandises", "K", K),
  e("66.19A", "Supports juridiques de gestion de patrimoine mobilier", "K", K),
  e("66.19B", "Autres activités auxiliaires de services financiers n.c.a.", "K", K),
  e("66.21Z", "Évaluation des risques et dommages", "K", K),
  e("66.22Z", "Activités des agents et courtiers d'assurances", "K", K),
  e("66.29Z", "Autres activités auxiliaires d'assurance et de caisses de retraite", "K", K),
  e("66.30Z", "Gestion de fonds", "K", K),

  // ── L — Immobilier ────────────────────────────────────────────────
  e("68.10Z", "Activités des marchands de biens immobiliers", "L", L),
  e("68.20A", "Location de logements", "L", L),
  e("68.20B", "Location de terrains et d'autres biens immobiliers", "L", L),
  e("68.31Z", "Agences immobilières", "L", L),
  e("68.32A", "Administration d'immeubles et autres biens immobiliers", "L", L),
  e("68.32B", "Supports juridiques de gestion de patrimoine immobilier", "L", L),

  // ── M — Activités spécialisées ────────────────────────────────────
  e("69.10Z", "Activités juridiques (avocats, notaires, huissiers…)", "M", M),
  e("69.20Z", "Activités comptables (experts-comptables, commissaires aux comptes…)", "M", M),
  e("70.10Z", "Activités des sièges sociaux", "M", M),
  e("70.21Z", "Conseil en relations publiques et communication", "M", M),
  e("70.22Z", "Conseil pour les affaires et autres conseils de gestion", "M", M),
  e("71.11Z", "Activités d'architecture", "M", M),
  e("71.12A", "Activités des géomètres", "M", M),
  e("71.12B", "Ingénierie, études techniques", "M", M),
  e("71.20A", "Contrôle technique automobile", "M", M),
  e("71.20B", "Analyses, essais et inspections techniques", "M", M),
  e("72.11Z", "Recherche-développement en biotechnologie", "M", M),
  e("72.19Z", "Recherche-développement en autres sciences physiques et naturelles", "M", M),
  e("72.20Z", "Recherche-développement en sciences humaines et sociales", "M", M),
  e("73.11Z", "Activités des agences de publicité", "M", M),
  e("73.12Z", "Régie publicitaire de médias", "M", M),
  e("73.20Z", "Études de marché et sondages", "M", M),
  e("74.10Z", "Activités spécialisées de design", "M", M),
  e("74.20Z", "Activités photographiques", "M", M),
  e("74.30Z", "Traduction et interprétation", "M", M),
  e("74.90A", "Activité des économistes de la construction", "M", M),
  e("74.90B", "Autres activités spécialisées, scientifiques et techniques n.c.a.", "M", M),
  e("75.00Z", "Activités vétérinaires", "M", M),

  // ── N — Services administratifs et de soutien ──────────────────────
  e("77.11A", "Location de courte durée de voitures et de véhicules automobiles légers", "N", N),
  e("77.11B", "Location de longue durée de voitures et de véhicules automobiles légers", "N", N),
  e("77.12Z", "Location et location-bail de camions", "N", N),
  e("77.21Z", "Location et location-bail d'articles de loisirs et de sport", "N", N),
  e("77.22Z", "Location de cassettes vidéo et disques vidéo", "N", N),
  e("77.29Z", "Location et location-bail d'autres biens personnels et domestiques", "N", N),
  e("77.31Z", "Location et location-bail de machines et équipements agricoles", "N", N),
  e("77.32Z", "Location et location-bail de machines et équipements pour la construction", "N", N),
  e("77.33Z", "Location et location-bail de machines de bureau et de matériel informatique", "N", N),
  e("77.34Z", "Location et location-bail de matériels de transport par eau", "N", N),
  e("77.35Z", "Location et location-bail de matériels de transport aérien", "N", N),
  e("77.39Z", "Location et location-bail d'autres machines, équipements et biens matériels n.c.a.", "N", N),
  e("77.40Z", "Location-bail de propriété intellectuelle et de produits similaires", "N", N),
  e("78.10Z", "Activités des agences de placement de main-d'œuvre", "N", N),
  e("78.20Z", "Activités des agences de travail temporaire", "N", N),
  e("78.30Z", "Autre mise à disposition de ressources humaines", "N", N),
  e("79.11Z", "Activités des agences de voyage", "N", N),
  e("79.12Z", "Activités des voyagistes", "N", N),
  e("79.90Z", "Autres services de réservation et activités connexes", "N", N),
  e("80.10Z", "Activités de sécurité privée", "N", N),
  e("80.20Z", "Activités liées aux systèmes de sécurité", "N", N),
  e("80.30Z", "Activités d'enquête", "N", N),
  e("81.10Z", "Activités combinées de soutien lié aux bâtiments (facility management)", "N", N),
  e("81.21Z", "Nettoyage courant des bâtiments", "N", N),
  e("81.22Z", "Autres activités de nettoyage des bâtiments et nettoyage industriel", "N", N),
  e("81.29A", "Désinfection, désinsectisation, dératisation", "N", N),
  e("81.29B", "Autres activités de nettoyage n.c.a.", "N", N),
  e("81.30Z", "Services d'aménagement paysager", "N", N),
  e("82.11Z", "Services administratifs combinés de bureau", "N", N),
  e("82.19Z", "Photocopie, préparation de documents et autres activités spécialisées de soutien de bureau", "N", N),
  e("82.20Z", "Activités de centres d'appels", "N", N),
  e("82.30Z", "Organisation de salons professionnels et de congrès", "N", N),
  e("82.91Z", "Activités des agences de recouvrement de factures et sociétés d'information financière", "N", N),
  e("82.92Z", "Activités de conditionnement", "N", N),
  e("82.99Z", "Autres activités de soutien aux entreprises n.c.a.", "N", N),

  // ── O — Administration publique et défense ────────────────────────
  e("84.11Z", "Administration publique générale", "O", O),
  e("84.12Z", "Administration publique (tutelle) de la santé, de la formation, de la culture et des services sociaux", "O", O),
  e("84.13Z", "Administration publique (tutelle) des activités économiques", "O", O),
  e("84.21Z", "Affaires étrangères", "O", O),
  e("84.22Z", "Défense", "O", O),
  e("84.23Z", "Justice", "O", O),
  e("84.24Z", "Activités d'ordre public et de sécurité", "O", O),
  e("84.25Z", "Services du feu et de secours", "O", O),
  e("84.30A", "Activités générales de sécurité sociale", "O", O),
  e("84.30B", "Gestion des retraites complémentaires", "O", O),
  e("84.30C", "Distribution sociale de revenus", "O", O),

  // ── P — Enseignement ──────────────────────────────────────────────
  e("85.10Z", "Enseignement pré-primaire", "P", P),
  e("85.20Z", "Enseignement primaire", "P", P),
  e("85.31Z", "Enseignement secondaire général", "P", P),
  e("85.32Z", "Enseignement secondaire technique ou professionnel", "P", P),
  e("85.41Z", "Enseignement post-secondaire non supérieur", "P", P),
  e("85.42Z", "Enseignement supérieur", "P", P),
  e("85.51Z", "Enseignement de disciplines sportives et d'activités de loisirs", "P", P),
  e("85.52Z", "Enseignement culturel", "P", P),
  e("85.53Z", "Enseignement de la conduite", "P", P),
  e("85.59A", "Formation continue d'adultes", "P", P),
  e("85.59B", "Autres enseignements n.c.a.", "P", P),
  e("85.60Z", "Activités de soutien à l'enseignement", "P", P),

  // ── Q — Santé humaine et action sociale ───────────────────────────
  e("86.10Z", "Activités hospitalières", "Q", Q),
  e("86.21Z", "Activité des médecins généralistes", "Q", Q),
  e("86.22A", "Activités de radiodiagnostic et de radiothérapie", "Q", Q),
  e("86.22B", "Activités chirurgicales", "Q", Q),
  e("86.22C", "Autres activités spécialisées des médecins", "Q", Q),
  e("86.23Z", "Pratique dentaire", "Q", Q),
  e("86.90A", "Ambulances", "Q", Q),
  e("86.90B", "Laboratoires d'analyses médicales", "Q", Q),
  e("86.90C", "Centres de collecte et banques d'organes", "Q", Q),
  e("86.90D", "Activités des infirmiers et des sages-femmes", "Q", Q),
  e("86.90E", "Activités des professionnels de la rééducation, de l'appareillage et des pédicures-podologues", "Q", Q),
  e("86.90F", "Activités de santé humaine non classées ailleurs", "Q", Q),
  e("87.10A", "Hébergement médicalisé pour personnes âgées (EHPAD)", "Q", Q),
  e("87.10B", "Hébergement médicalisé pour enfants handicapés", "Q", Q),
  e("87.10C", "Hébergement médicalisé pour adultes handicapés", "Q", Q),
  e("87.20A", "Hébergement social pour handicapés mentaux et malades mentaux", "Q", Q),
  e("87.20B", "Hébergement social pour toxicomanes", "Q", Q),
  e("87.30A", "Hébergement social pour personnes âgées", "Q", Q),
  e("87.30B", "Hébergement social pour handicapés physiques", "Q", Q),
  e("87.90A", "Hébergement social pour enfants en difficulté", "Q", Q),
  e("87.90B", "Hébergement social pour adultes et familles en difficulté", "Q", Q),
  e("88.10A", "Aide à domicile", "Q", Q),
  e("88.10B", "Accueil ou accompagnement sans hébergement d'adultes handicapés ou de personnes âgées", "Q", Q),
  e("88.10C", "Aide par le travail", "Q", Q),
  e("88.91A", "Accueil de jeunes enfants (crèches, haltes-garderies)", "Q", Q),
  e("88.91B", "Accueil ou accompagnement sans hébergement d'enfants handicapés", "Q", Q),
  e("88.99A", "Autre accueil ou accompagnement sans hébergement d'enfants et d'adolescents", "Q", Q),
  e("88.99B", "Action sociale sans hébergement n.c.a.", "Q", Q),

  // ── R — Arts, spectacles et activités récréatives ─────────────────
  e("90.01Z", "Arts du spectacle vivant", "R", R),
  e("90.02Z", "Activités de soutien au spectacle vivant", "R", R),
  e("90.03A", "Création artistique relevant des arts plastiques", "R", R),
  e("90.03B", "Autre création artistique", "R", R),
  e("90.04Z", "Gestion de salles de spectacles et production de spectacles", "R", R),
  e("91.01Z", "Gestion des bibliothèques et des archives", "R", R),
  e("91.02Z", "Gestion des musées", "R", R),
  e("91.03Z", "Gestion des sites et monuments historiques et attractions touristiques similaires", "R", R),
  e("91.04Z", "Gestion des jardins botaniques et zoologiques et des réserves naturelles", "R", R),
  e("92.00Z", "Organisation de jeux de hasard et d'argent", "R", R),
  e("93.11Z", "Gestion d'installations sportives", "R", R),
  e("93.12Z", "Activités de clubs de sports", "R", R),
  e("93.13Z", "Activités des centres de culture physique", "R", R),
  e("93.19Z", "Autres activités liées au sport", "R", R),
  e("93.21Z", "Activités des parcs d'attractions et parcs à thèmes", "R", R),
  e("93.29Z", "Autres activités récréatives et de loisirs", "R", R),

  // ── S — Autres activités de services ─────────────────────────────
  e("94.11Z", "Activités des organisations patronales et consulaires", "S", S),
  e("94.12Z", "Activités des organisations professionnelles", "S", S),
  e("94.20Z", "Activités des syndicats de salariés", "S", S),
  e("94.91Z", "Activités des organisations religieuses", "S", S),
  e("94.92Z", "Activités des organisations politiques", "S", S),
  e("94.99Z", "Activités des autres organisations associatives n.c.a.", "S", S),
  e("95.11Z", "Réparation d'ordinateurs et d'équipements périphériques", "S", S),
  e("95.12Z", "Réparation d'équipements de communication", "S", S),
  e("95.21Z", "Réparation de produits électroniques grand public", "S", S),
  e("95.22Z", "Réparation d'appareils électroménagers et d'équipements pour la maison et le jardin", "S", S),
  e("95.23Z", "Réparation de chaussures et d'articles en cuir", "S", S),
  e("95.24Z", "Réparation de meubles et d'articles d'ameublement", "S", S),
  e("95.25Z", "Réparation d'articles d'horlogerie et de bijouterie", "S", S),
  e("95.29Z", "Réparation d'autres biens personnels et domestiques", "S", S),
  e("96.01A", "Blanchisserie-teinturerie de gros", "S", S),
  e("96.01B", "Blanchisserie-teinturerie de détail", "S", S),
  e("96.02A", "Coiffure", "S", S),
  e("96.02B", "Soins de beauté", "S", S),
  e("96.03Z", "Services funéraires", "S", S),
  e("96.04Z", "Entretien corporel (spas, thalassothérapie, hammam…)", "S", S),
  e("96.09Z", "Autres services personnels n.c.a.", "S", S),

  // ── T — Activités des ménages ────────────────────────────────────
  e("97.00Z", "Activités des ménages en tant qu'employeurs de personnel domestique", "T", T),
  e("98.10Z", "Activités indifférenciées des ménages en tant que producteurs de biens pour usage propre", "T", T),
  e("98.20Z", "Activités indifférenciées des ménages en tant que producteurs de services pour usage propre", "T", T),

  // ── U — Activités extraterritoriales ────────────────────────────
  e("99.00Z", "Activités des organisations et organismes extraterritoriaux", "U", U),
];

/**
 * Mapping secteur CRM → codes NAF pertinents.
 * Utilisé pour filtrer intelligemment les codes NAF selon le secteur sélectionné.
 */
export const SECTOR_NAF_MAP: Record<string, string[]> = {
  hotel: [
    "55.10Z", "55.20Z", "55.30Z", "55.90Z",
    "79.11Z", "79.12Z", "79.90Z",
    "93.29Z",
  ],
  restauration: [
    "56.10A", "56.10B", "56.10C", "56.21Z", "56.29A", "56.29B", "56.30Z",
    "10.71A", "10.71B", "10.71C", "10.71D", "10.72Z",
    "46.17A", "46.34Z", "46.36Z", "46.37Z",
    "47.24Z", "47.25Z", "47.29Z",
  ],
  logistique: [
    "49.10Z", "49.20Z", "49.39A", "49.39B", "49.41A", "49.41B", "49.41C", "49.42Z", "49.50Z",
    "50.10Z", "50.20Z", "50.30Z", "50.40Z",
    "51.10Z", "51.21Z", "51.22Z",
    "52.10A", "52.10B", "52.21Z", "52.22Z", "52.23Z", "52.24A", "52.24B", "52.29A", "52.29B",
    "53.10Z", "53.20Z",
    "77.12Z", "77.34Z", "77.35Z", "77.39Z",
  ],
  retail: [
    "47.11A", "47.11B", "47.11C", "47.11D", "47.11E", "47.11F",
    "47.19A", "47.19B",
    "47.21Z", "47.22Z", "47.23Z", "47.24Z", "47.25Z", "47.26Z", "47.29Z", "47.30Z",
    "47.41Z", "47.42Z", "47.43Z",
    "47.51Z", "47.52A", "47.52B", "47.53Z", "47.54Z", "47.59A", "47.59B",
    "47.61Z", "47.62Z", "47.63Z", "47.64Z", "47.65Z",
    "47.71Z", "47.72A", "47.72B", "47.73Z", "47.74Z", "47.75Z", "47.76Z", "47.77Z",
    "47.78A", "47.78B", "47.78C", "47.79Z",
    "47.81Z", "47.82Z", "47.89Z",
    "47.91A", "47.91B", "47.99A", "47.99B",
    "45.11Z", "45.19Z", "45.31Z", "45.32Z", "45.40Z",
    "46.11Z", "46.17A", "46.17B", "46.19A", "46.19B",
  ],
  industrie: [
    "10.11Z", "10.12Z", "10.13A", "10.13B", "10.20Z", "10.31Z", "10.32Z",
    "10.41A", "10.41B", "10.42Z", "10.51A", "10.51B", "10.51C", "10.51D", "10.52Z",
    "10.61A", "10.61B", "10.62Z", "10.81Z", "10.82Z", "10.83Z", "10.84Z", "10.85Z", "10.86Z", "10.89Z",
    "10.91Z", "10.92Z", "11.01Z", "11.02A", "11.02B", "11.03Z", "11.04Z", "11.05Z", "11.06Z", "11.07A", "11.07B",
    "12.00Z",
    "13.10Z", "13.20Z", "13.30Z", "13.91Z", "13.92Z", "13.93Z", "13.94Z", "13.95Z", "13.96Z", "13.99Z",
    "14.11Z", "14.12Z", "14.13Z", "14.14Z", "14.19Z",
    "15.11Z", "15.12Z", "15.20Z",
    "16.10A", "16.10B", "16.21Z", "16.22Z", "16.23Z", "16.24Z", "16.29Z",
    "17.11Z", "17.12Z", "17.21A", "17.21B", "17.21C", "17.22Z", "17.23Z", "17.29Z",
    "18.12Z", "18.13Z", "18.14Z",
    "19.10Z", "19.20Z",
    "20.11Z", "20.12Z", "20.13B", "20.14Z", "20.15Z", "20.16Z", "20.17Z", "20.20Z", "20.30Z",
    "20.41Z", "20.42Z", "20.52Z", "20.53Z", "20.59Z", "20.60Z",
    "21.10Z", "21.20Z",
    "22.11Z", "22.19Z", "22.21Z", "22.22Z", "22.23Z", "22.29A", "22.29B",
    "23.11Z", "23.12Z", "23.13Z", "23.14Z", "23.19Z", "23.31Z", "23.32Z",
    "23.41Z", "23.51Z", "23.52Z", "23.61Z", "23.62Z", "23.63Z", "23.64Z", "23.65Z", "23.69Z",
    "23.70Z", "23.91Z", "23.99Z",
    "24.10Z", "24.20Z", "24.31Z", "24.32Z", "24.33Z", "24.34Z",
    "24.41Z", "24.42Z", "24.43Z", "24.44Z", "24.45Z",
    "24.51Z", "24.52Z", "24.53Z", "24.54Z",
    "25.11Z", "25.12Z", "25.21Z", "25.29Z", "25.30Z", "25.40Z", "25.50A", "25.50B",
    "25.61Z", "25.62A", "25.62B", "25.71Z", "25.72Z", "25.73A", "25.73B",
    "25.91Z", "25.92Z", "25.93Z", "25.94Z", "25.99A", "25.99B",
    "26.11Z", "26.12Z", "26.20Z", "26.30Z", "26.40Z", "26.51A", "26.51B", "26.52Z",
    "26.60Z", "26.70Z", "26.80Z",
    "27.11Z", "27.12Z", "27.20Z", "27.31Z", "27.32Z", "27.33Z", "27.40Z", "27.51Z", "27.52Z", "27.90Z",
    "28.11Z", "28.12Z", "28.13Z", "28.14Z", "28.15Z", "28.21Z", "28.22Z", "28.23Z", "28.24Z", "28.25Z",
    "28.29A", "28.29B", "28.30Z", "28.41Z", "28.49Z",
    "28.91Z", "28.92Z", "28.93Z", "28.94Z", "28.95Z", "28.96Z", "28.99A", "28.99B",
    "29.10Z", "29.20Z", "29.31Z", "29.32Z",
    "30.11Z", "30.12Z", "30.20Z", "30.30Z", "30.40Z", "30.91Z", "30.92Z", "30.99Z",
    "31.01Z", "31.02Z", "31.03Z", "31.09A", "31.09B",
    "32.11Z", "32.12Z", "32.13Z", "32.20Z", "32.30Z", "32.40Z", "32.50A", "32.50B", "32.91Z", "32.99Z",
    "33.11Z", "33.12Z", "33.13Z", "33.14Z", "33.15Z", "33.16Z", "33.17Z", "33.19Z",
    "33.20A", "33.20B", "33.20C", "33.20D",
  ],
  immo: [
    "41.10A", "41.10B", "41.10C", "41.10D",
    "68.10Z", "68.20A", "68.20B", "68.31Z", "68.32A", "68.32B",
    "66.19A", "66.19B",
  ],
  services: [
    "69.10Z", "69.20Z",
    "70.10Z", "70.21Z", "70.22Z",
    "71.11Z", "71.12A", "71.12B", "71.20A", "71.20B",
    "73.11Z", "73.12Z", "73.20Z",
    "74.10Z", "74.20Z", "74.30Z", "74.90A", "74.90B",
    "75.00Z",
    "77.11A", "77.11B", "77.21Z", "77.29Z", "77.31Z", "77.32Z", "77.33Z", "77.39Z", "77.40Z",
    "78.10Z", "78.20Z", "78.30Z",
    "79.11Z", "79.12Z", "79.90Z",
    "80.10Z", "80.20Z", "80.30Z",
    "81.10Z", "81.21Z", "81.22Z", "81.29A", "81.29B", "81.30Z",
    "82.11Z", "82.19Z", "82.20Z", "82.30Z", "82.91Z", "82.92Z", "82.99Z",
    "94.11Z", "94.12Z",
    "96.01A", "96.01B", "96.02A", "96.02B", "96.03Z", "96.04Z", "96.09Z",
  ],
  tech: [
    "58.21Z", "58.29A", "58.29B", "58.29C",
    "61.10Z", "61.20Z", "61.30Z", "61.90Z",
    "62.01Z", "62.02A", "62.02B", "62.03Z", "62.09Z",
    "63.11Z", "63.12Z", "63.99Z",
    "26.11Z", "26.12Z", "26.20Z", "26.30Z", "26.40Z", "26.51A", "26.51B",
    "46.51Z", "46.52Z",
    "47.41Z", "47.42Z", "47.43Z",
    "72.11Z", "72.19Z",
  ],
  sante: [
    "21.10Z", "21.20Z",
    "26.60Z",
    "32.50A", "32.50B",
    "46.46Z",
    "47.73Z", "47.74Z",
    "86.10Z", "86.21Z", "86.22A", "86.22B", "86.22C", "86.23Z",
    "86.90A", "86.90B", "86.90C", "86.90D", "86.90E", "86.90F",
    "87.10A", "87.10B", "87.10C",
    "87.20A", "87.20B",
    "87.30A", "87.30B",
    "87.90A", "87.90B",
    "88.10A", "88.10B", "88.10C",
    "88.91A", "88.91B", "88.99A", "88.99B",
  ],
  education: [
    "58.11Z", "58.12Z", "58.14Z", "58.19Z",
    "72.20Z",
    "85.10Z", "85.20Z", "85.31Z", "85.32Z", "85.41Z", "85.42Z",
    "85.51Z", "85.52Z", "85.53Z", "85.59A", "85.59B", "85.60Z",
    "91.01Z",
  ],
  finance: [
    "64.11Z", "64.19Z", "64.20Z", "64.30Z", "64.91Z", "64.92Z", "64.99Z",
    "65.11Z", "65.12Z", "65.20Z", "65.30Z",
    "66.11Z", "66.12Z", "66.19A", "66.19B", "66.21Z", "66.22Z", "66.29Z", "66.30Z",
    "69.20Z",
    "82.91Z",
  ],
  btp: [
    "41.10A", "41.10B", "41.10C", "41.10D",
    "41.20A", "41.20B",
    "42.11Z", "42.12Z", "42.13A", "42.13B", "42.21Z", "42.22Z", "42.91Z", "42.99Z",
    "43.11Z", "43.12A", "43.12B", "43.13Z",
    "43.21A", "43.21B", "43.22A", "43.22B", "43.29A", "43.29B",
    "43.31Z", "43.32A", "43.32B", "43.32C", "43.33Z", "43.34Z", "43.39Z",
    "43.91A", "43.91B", "43.99A", "43.99B", "43.99C", "43.99D", "43.99E",
    "23.51Z", "23.52Z", "23.61Z", "23.62Z", "23.63Z", "23.64Z", "23.65Z", "23.69Z", "23.70Z",
    "25.11Z", "25.12Z",
    "46.73A", "46.73B", "46.74A", "46.74B",
    "47.52A", "47.52B",
    "71.11Z", "71.12A", "71.12B",
    "74.90A",
    "77.32Z",
  ],
  agriculture: [
    "01.11Z", "01.12Z", "01.13A", "01.13B", "01.14Z", "01.15Z", "01.16Z", "01.19Z",
    "01.21Z", "01.22Z", "01.23Z", "01.24Z", "01.25Z", "01.26Z", "01.27Z", "01.28Z", "01.29Z", "01.30Z",
    "01.41Z", "01.42Z", "01.43Z", "01.44Z", "01.45Z", "01.46Z", "01.47Z", "01.49Z", "01.50Z",
    "01.61Z", "01.62Z", "01.63Z", "01.64Z", "01.70Z",
    "02.10Z", "02.20Z", "02.30Z", "02.40Z",
    "03.11Z", "03.12Z", "03.21Z", "03.22Z",
    "10.11Z", "10.12Z", "10.13A", "10.13B",
    "10.31Z", "10.32Z", "10.39A", "10.39B",
    "10.41A", "10.41B", "10.51A", "10.51B", "10.51C", "10.51D",
    "10.61A", "10.61B", "10.91Z", "10.92Z",
    "11.02A", "11.02B", "11.03Z", "11.04Z", "11.05Z", "11.06Z",
    "20.15Z", "20.20Z",
    "28.30Z",
    "46.21Z", "46.22Z", "46.23Z", "46.24Z", "46.31Z",
    "47.76Z", "47.81Z",
    "77.31Z",
  ],
  energie: [
    "05.10Z", "05.20Z", "06.10Z", "06.20Z",
    "07.10Z", "07.21Z", "07.29Z",
    "08.91Z", "08.92Z", "09.10Z",
    "19.10Z", "19.20Z",
    "20.11Z",
    "24.46Z",
    "35.11Z", "35.12Z", "35.13Z", "35.14Z",
    "35.21Z", "35.22Z", "35.23Z", "35.30Z",
    "36.00Z", "37.00Z",
    "38.11Z", "38.12Z", "38.21Z", "38.22Z", "38.31Z", "38.32Z", "39.00Z",
    "42.21Z", "43.22B",
    "46.71Z", "46.72Z", "46.75Z",
  ],
  culture: [
    "58.11Z", "58.13Z", "58.14Z", "58.19Z",
    "59.11A", "59.11B", "59.11C", "59.12Z", "59.13A", "59.13B", "59.14Z",
    "59.20Z",
    "60.10Z", "60.20A", "60.20B",
    "63.91Z",
    "74.10Z", "74.20Z",
    "90.01Z", "90.02Z", "90.03A", "90.03B", "90.04Z",
    "91.01Z", "91.02Z", "91.03Z", "91.04Z",
    "92.00Z",
    "93.11Z", "93.12Z", "93.13Z", "93.19Z", "93.21Z", "93.29Z",
    "47.61Z", "47.62Z", "47.63Z", "47.64Z", "47.65Z",
    "32.20Z", "32.30Z", "32.40Z",
  ],
};
